In [1]:
import numpy as np
a=np.array([5,6,9])
a[0]

5

In [2]:
a[1]

6

In [4]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [9]:
a=np.array([5,6,9])
a.ndim

1

In [6]:
a.itemsize

4

In [7]:
a=np.array([[1,2],[3,4],[5,6]])
a.itemsize

4

In [10]:
a.dtype

dtype('int32')

In [11]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a.itemsize

8

In [12]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [13]:
a.size

6

In [14]:
a.shape

(3, 2)

In [15]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
l=range(5)
l[0]

0

In [19]:
l[1]

1

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,5,2)

array([1, 3])

In [22]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [24]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [25]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a.shape

(3, 2)

In [27]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [30]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
a.min()

1

In [32]:
a.max()

6

In [33]:
a.sum()

21

In [34]:
a.sum(axis=0)

array([ 9, 12])

In [35]:
a.sum(axis=1)

array([ 3,  7, 11])

In [36]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [37]:
np.std(a)

1.707825127659933

In [39]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a

array([[1, 2],
       [3, 4]])

In [40]:
b

array([[5, 6],
       [7, 8]])

In [41]:
a+b


array([[ 6,  8],
       [10, 12]])

In [42]:
a-b

array([[-4, -4],
       [-4, -4]])

In [43]:
a*b

array([[ 5, 12],
       [21, 32]])

In [44]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [45]:
a.dot(b)

array([[19, 22],
       [43, 50]])